// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT4b7g5S71WP0xCrDWsHJ5DBZbDtCyS6c',
    appId: '1:272817537986:web:1bf3bf570da217bec10c5b',
    messagingSenderId: '272817537986',
    projectId: 'safeconnect-e60a3',
    authDomain: 'safeconnect-e60a3.firebaseapp.com',
    databaseURL: 'https://safeconnect-e60a3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safeconnect-e60a3.firebasestorage.app',
    measurementId: 'G-BK0CMM4LXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4bbsFfngFlxjsV8TK1SAlE8S0HQwffSQ',
    appId: '1:272817537986:android:eb3af41dfb77fcc6c10c5b',
    messagingSenderId: '272817537986',
    projectId: 'safeconnect-e60a3',
    databaseURL: 'https://safeconnect-e60a3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safeconnect-e60a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkTJZW_YROTh8ddY7AeEyK5u26Zw2P1s0',
    appId: '1:272817537986:ios:d5e623c5e55e49f3c10c5b',
    messagingSenderId: '272817537986',
    projectId: 'safeconnect-e60a3',
    databaseURL: 'https://safeconnect-e60a3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safeconnect-e60a3.firebasestorage.app',
    iosBundleId: 'com.example.safeconnect',
  );

}